version: '3'

services:
    iacode:
        container_name: iacode
        build:
            context: ./iacode/
            dockerfile: Dockerfile
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix 
            - /iacode_data:/usr/src/iacode
            

        ports:
            - "72:22"
            - "5601:5601"
        networks:
            - iacode
        tty: true
        privileged: true
        environment:
            - DISPLAY=localhost:1.0
            
            
networks:
    iacode:
        driver: bridge
