apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data4
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data4"
