apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "kibana"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: kibana
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "kibanaesarticle-kibana"
              servicePort: 5601
