
data "template_file" "json_config" {
    
    template = <<EOF
{
    "endpoint": "${module.eks.cluster_endpoint}",
    "securitygroup": "${module.eks.cluster_security_group_id}",
    "kubectl_config": "${module.eks.kubeconfig}"
    

}
EOF
}



resource "local_file" "environment1" {
    content = "${data.template_file.json_config.rendered}"
    filename = "../terraform/modules_data/k8s-manager-ksc/json.secret"
    file_permission = "0400"
}  



output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}
